name: deploy production
push:
  branches:
    - master
jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - name: deployscript
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        key: ${{ secrets.KEY }}
        port: ${{ secrets.PORT }}
        passphrase: ${{ secrets.PASSPHRASE }}
        script: cd babbelbox && git pull && ./docker-run.sh
